### ISSUE TITLE
Create Documentation: 'How to Set up a Blockstack Node on Raspberry Pi"

### ISSUE THREAD

**Issue by blockstackers** [blockstackers/pox_pm#10]
- [ ] Draft documentation based on livestream with Dan Trevino **by 04/14/20**
- [ ] Submit draft to Testnet Ambassadors to test and provide feedback **by 04/15/20**
- [ ] Edit and revise docs **by 04/20/20**
- [ ] Publish to Blockstack's official docs **by 04/21/20**
- [ ] After publication: share with the broader Blockstack community

**Comment by whoabuddy** [comment]
The basic instructions are in Dan's repo: 
https://github.com/dantrevino/cross-compiling-stacks-blockchain
