### ISSUE TITLE
Set up local testnet in preparation for the Stacks 2.0 public testnet

### ISSUE THREAD

**Issue by blockstackers** [blockstackers/pox_pm#11]
- Make sure to have Rust and Cargo installed
- Go through https://github.com/blockstack/stacks-blockchain#getting-started

**Comment by whoabuddy** [comment]
I remember doing this successfully on my laptop, so I thought I'd give a try from a virtual machine.

Using Linux Mint 19.3 XFCE with 2gb of RAM got stuck for over two hours during `cargo test` and I finally gave up. :slightly_frowning_face: 

Trying it now with 3gb, but `cargo test` still taking quite a while (just passing 30min mark) and stuck on build step 222/223. Thankfully this was not a live stream! :zzz: 

I did want to note a few extra dependencies. On Linux Mint (Ubuntu-derived) I had to install the following with `apt-get` first before the cargo commands would run correctly:
- build-essential
- cmake
- git
- libssl-dev

I have a markdown file with extra steps from start to finish similar to that found on the stacks-blockchain repo, and I will share it once I get through this test on the VM - not sure what is causing it to hang at this point but I'll let it keep crunching away while I do other things!!
