### ISSUE TITLE
Live testnet demo during community town hall on 04/24/20

### ISSUE THREAD

**Issue by blockstackers** [blockstackers/pox_pm#15]
- [x] Need 1 ambassador to demo testnet setup during the community town hall on Friday, April 24th at 10:00am EST. (Please volunteer in the comments.)

**Support:** 
- A PBC engineer will be online to help answer questions from community members

**Deadline to volunteer: 04/20/20**

**Comment by friedger** [comment]
I am in.

**Comment by blockstackers** [comment]
Nice, thanks @friedger!
